# Generated by Django 5.2 on 2025-05-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brightfurnitureuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='brightfurnitureuser',
            name='password',
        ),
        migrations.AddField(
            model_name='brightfurnitureuser',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
