# Generated by Django 5.2 on 2025-05-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_brightfurnitureuser_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FurnitureData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furniture_img', models.ImageField(upload_to='furniture_images/')),
                ('furniture_name', models.CharField(max_length=100)),
                ('furniture_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('furniture_description', models.TextField()),
                ('furniture_category', models.CharField(max_length=50)),
            ],
        ),
    ]
