# Generated by Django 5.2 on 2025-05-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_furnituredata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnituredata',
            name='furniture_img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
